name: gt2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - bcftools=1.20
  - coreutils=9.1
  - mafft
  - minimap2=2.17
  - samtools=1.20
  - tabix=1.11
  - blast

